import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PageTransitionProvider from "../ui/PageTransitionProvider";
import Header from "@/component/Header";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const avone = localFont({
  src: "./fonts/AVONE.ttf",
  variable: "--font-avone",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${avone.variable} h-full antialiased`}
    >
      <body className="min-h-screen">
        <PageTransitionProvider>
          {/* <Header /> */}
          {children}
        </PageTransitionProvider>
      </body>
    </html>
  );
}
